In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
folder = "Julien"
track_data = pd.read_json(folder + '/track_data.json')
track_data = track_data.loc[["danceability","energy","loudness","speechiness","acousticness","instrumentalness","liveness","valence", "tempo","duration_ms","popularity","artist","album"]].T #"key","mode"
track_data.head()

danceability energy loudness speechiness acousticness  \
Like I Do              0.635    0.9   -3.719      0.0377      0.00664   
Comme dit maman        0.792  0.711   -6.243      0.0561        0.791   
Salzburg               0.847  0.346  -11.243      0.0936      0.00339   
Offshore                0.82  0.435   -9.157       0.303        0.724   
Khapta                 0.811  0.692   -2.836       0.105      0.00937   

                instrumentalness liveness valence    tempo duration_ms  \
Like I Do                 0.0145     0.37    0.15  127.978      202500   
Comme dit maman                0    0.102     0.7  144.131      187106   
Salzburg                   0.918   0.0704   0.404  126.009      436150   
Offshore                       0    0.317    0.51  124.006      206747   
Khapta                         0   0.0598   0.817  125.009      162907   

                popularity                                 artist  \
Like I Do               68  [David Guetta, Martin Garrix, Brooks]   
Comme dit maman         41              [Hayce Lemsi, Volts Face]   
Salzburg                57                              [Worakls]   
Offshore                48                 [Vald, Suikon Blaz AD]   
Khapta                  62             [Heuss L'enfoiré, Sofiane]   

                           album  
Like I Do              Like I Do  
Comme dit maman  Comme dit maman  
Salzburg                Salzburg  
Offshore                     XEU  
Khapta                 En esprit

In [3]:
track_np = np.array(track_data.values[:,:-2])
print(track_np)

[[0.635 0.9 -3.719 ... 127.978 202500 68]
 [0.792 0.711 -6.243 ... 144.131 187106 41]
 [0.847 0.34600000000000003 -11.243 ... 126.009 436150 57]
 ...
 [0.487 0.398 -9.901 ... 149.367 157766 71]
 [0.873 0.719 -5.948 ... 93.281 307773 77]
 [0.6920000000000001 0.8180000000000001 -4.4 ... 96.05 241875 52]]


In [6]:
from sklearn.preprocessing import MinMaxScaler

minMaxScaler = MinMaxScaler().fit(track_np)
track_np = minMaxScaler.transform(track_np)

print(track_np)

[[0.62805763 0.90899796 0.87265411 ... 0.45445066 0.30207715 0.69387755]
 [0.80341785 0.71574642 0.79512854 ... 0.56242021 0.27505696 0.41836735]
 [0.86484977 0.34253579 0.64155174 ... 0.44128951 0.71218945 0.58163265]
 ...
 [0.46274992 0.39570552 0.68277175 ... 0.59741857 0.22355816 0.7244898 ]
 [0.89389032 0.72392638 0.80418958 ... 0.22252969 0.48685675 0.78571429]
 [0.69172344 0.82515337 0.85173695 ... 0.24103819 0.37118981 0.53061224]]


In [7]:
track_data_normalized = pd.DataFrame(track_np,columns=track_data.columns[:-2],index=track_data.index)
track_data_normalized.head()

danceability    energy  loudness  speechiness  acousticness  \
Like I Do            0.628058  0.908998  0.872654     0.016407      0.006668   
Comme dit maman      0.803418  0.715746  0.795129     0.037970      0.797374   
Salzburg             0.864850  0.342536  0.641552     0.081917      0.003392   
Offshore             0.834692  0.433538  0.705624     0.327317      0.729832   
Khapta               0.824640  0.696319  0.899776     0.095277      0.009420   

                 instrumentalness  liveness   valence     tempo  duration_ms  \
Like I Do                0.014781  0.376635  0.139853  0.454451     0.302077   
Comme dit maman          0.000000  0.084568  0.718191  0.562420     0.275057   
Salzburg                 0.935780  0.050131  0.406940  0.441290     0.712189   
Offshore                 0.000000  0.318875  0.518402  0.427901     0.309532   
Khapta                   0.000000  0.038579  0.841220  0.434605     0.232582   

                 popularity  
Like I Do          0.693878  
Comme dit maman    0.418367  
Salzburg           0.581633  
Offshore           0.489796  
Khapta             0.632653

In [8]:
track_data_normalized["artist"] = track_data["artist"]
track_data_normalized["album"] = track_data["album"]
track_data_normalized.head()

danceability    energy  loudness  speechiness  acousticness  \
Like I Do            0.628058  0.908998  0.872654     0.016407      0.006668   
Comme dit maman      0.803418  0.715746  0.795129     0.037970      0.797374   
Salzburg             0.864850  0.342536  0.641552     0.081917      0.003392   
Offshore             0.834692  0.433538  0.705624     0.327317      0.729832   
Khapta               0.824640  0.696319  0.899776     0.095277      0.009420   

                 instrumentalness  liveness   valence     tempo  duration_ms  \
Like I Do                0.014781  0.376635  0.139853  0.454451     0.302077   
Comme dit maman          0.000000  0.084568  0.718191  0.562420     0.275057   
Salzburg                 0.935780  0.050131  0.406940  0.441290     0.712189   
Offshore                 0.000000  0.318875  0.518402  0.427901     0.309532   
Khapta                   0.000000  0.038579  0.841220  0.434605     0.232582   

                 popularity                                 artist  \
Like I Do          0.693878  [David Guetta, Martin Garrix, Brooks]   
Comme dit maman    0.418367              [Hayce Lemsi, Volts Face]   
Salzburg           0.581633                              [Worakls]   
Offshore           0.489796                 [Vald, Suikon Blaz AD]   
Khapta             0.632653             [Heuss L'enfoiré, Sofiane]   

                           album  
Like I Do              Like I Do  
Comme dit maman  Comme dit maman  
Salzburg                Salzburg  
Offshore                     XEU  
Khapta                 En esprit

In [9]:
track_data_normalized.T.to_json(folder + '/track_data_normalized.json')

In [10]:
# from sklearn.cluster import KMeans
# n_clusters = 10
# kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(track_np)

# cluster_labels = kmeans.labels_

In [11]:
# music_clustered = [[] for k in range(n_clusters)]
# for i in range(track_data.shape[0]):
#     music_clustered[cluster_labels[i]].append(track_data.index[i])

In [13]:
# music_clustered

In [14]:
# track_data_normalized.mean()

danceability        0.674549
energy              0.661444
loudness            0.764635
speechiness         0.120826
acousticness        0.247908
instrumentalness    0.098190
liveness            0.180229
valence             0.485158
tempo               0.419224
duration_ms         0.315497
popularity          0.614082
dtype: float64